### ISSUE TITLE
[Feature Suggestion] Actionbar reminder of your active kick triggers

### ISSUE THREAD

**Issue by lerokko** [asdanjer/slotcrafter#1]
New unintrusive reminders for players that have `/yeetme` or `/takemyslot` enabled

Actionbar text that flashes every X seconds "Lag-Autokick active. _/yeetme_ to toggle off"
Actionbar text that flashes every X seconds "Slot-Surrender active. _/takemyslot_ to toggle off"
If the player has both active then it would just flash them both after another (hence they both can only have the same interval)

Additonally an actionbar text that flashes every Y seconds if mspt is above Z "High MSPT. Avoid laggy areas if possible"

Suggested new config values:
```
ReminderInterval
HighMSPTWarningInterval
YeetmeMessage
TakemyslotMessage
HighMSPTWarningMessage
```

**Comment by asdanjer** [comment]
https://github.com/asdanjer/slotcrafter/compare/1ac1ab26c3f393018fb6c46e0c95a6b75c1af3c7...d0a847e75ca66a7969706a26a8723411d5a14af5
added.

**Comment by lerokko** [comment]
What are the default values? It seems there are no default config entries

**Comment by asdanjer** [comment]
> What are the default values? It seems there are no default config entries

they are listed in the readme. you can also delete the config and then let it regenerate. then you can overwrite the vallues you already had again. 
if a config exists spigot dosn't overwrite it even if there is new stuff. 
or just copy the default config directly: 
https://github.com/asdanjer/slotcrafter/blob/master/src/main/resources/config.yml
